from .severidad_de_problemas_mentales import severidad_de_problemas_mentales
from .terapia_de_personas_con_problemas_mentales import terapia_de_personas_con_problemas_mentales
from .salud_mental_por_edad import salud_mental_edades
from .salud_mental_genero import salud_mental_genero
from .salud_mental_por_nivel_de_estres import salud_mental_por_nivel_de_estres

